# Generated by Django 3.2.7 on 2022-01-10 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('race_date', models.DateField(blank=True, null=True, verbose_name='date of race')),
            ],
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.CharField(default='u', max_length=1, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.DurationField(default=0, null=True)),
                ('member', models.CharField(default='n', max_length=2, null=True)),
                ('member_first_name', models.CharField(blank=True, default='unknown', max_length=200)),
                ('member_last_name', models.CharField(blank=True, default='unknown', max_length=200)),
                ('category_10', models.CharField(default='unknown', max_length=100, null=True)),
                ('points', models.IntegerField(default=0, null=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raceresults.race')),
                ('runner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='raceresults.runner')),
            ],
        ),
    ]
