# Generated by Django 3.1.5 on 2021-03-09 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raceresults', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='runner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='raceresults.runner'),
        ),
    ]
