# Generated by Django 3.1.5 on 2021-03-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raceresults', '0002_auto_20210309_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='date_race',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of race'),
        ),
    ]
