# Generated by Django 3.1.5 on 2021-03-12 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raceresults', '0004_auto_20210312_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='date_race',
            new_name='race_date',
        ),
    ]
