# Generated by Django 3.2.7 on 2021-10-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raceresults', '0009_result_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='member_first_name',
            field=models.CharField(blank=True, default='unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='result',
            name='member_last_name',
            field=models.CharField(blank=True, default='unknown', max_length=200),
        ),
    ]
